### ISSUE TITLE
Can't compile on macOS Sierra

### ISSUE THREAD

**Issue by klefevre** [swiftlyfalling/SQLiteLib#9]
The amalgamation script doesn't work on macOS Sierra for both the simulator and the device.

<img width="750" alt="capture d ecran 2016-09-22 a 17 48 34" src="https://cloud.githubusercontent.com/assets/1300874/18755522/e35ac9c0-80ec-11e6-8bd5-bf0489010ea2.png">

Any idea how to fix this ?

**Comment by swiftlyfalling** [comment]
Thank you for the report - looking into this.

**Comment by swiftlyfalling** [comment]
Please give the latest commit 5b31853 a try.

**Comment by swiftlyfalling** [comment]
@klefevre: Please give the latest commit 5b31853 a try.

**Comment by klefevre** [comment]
All good for me 👌 Thank you

**Comment by swiftlyfalling** [comment]
The `./configure` script was attempting to cross-compile targets, and part of the process ended up trying to run a C program that was compiled for the iPhone Simulator... on the local machine, which failed.

Since the amalgamation build process runs on the local machine, forcing it to build for macOS and use the macOS SDK fixed the issue.

This just affects the amalgamation target that generates the sqlite3.c file. The sqlitelib target then takes that generated source file and builds for whichever platform/SDK you select.
